### ISSUE TITLE
need a demo

### ISSUE THREAD

**Issue by qingtong234** [gabceb/redux-persist-transform-expire#4]
Hi, @gabceb:

I find these code is the repo: 
```
if (dateToUnix(new Date(expireDate)) < dateToUnix(new Date())) {
        this.update(config.defaultState);
      }
```
but I can't find where the `update` come from, can you give me some suggesion?

**Comment by gabceb** [comment]
Details please

**Comment by sospedra** [comment]
It's from https://github.com/substack/js-traverse

In this scenario is replacing the `expired` state for the `config.defaultState` one
